### PR TITLE
Update hosts.txt

### PR DESCRIPTION
**Pull request by stoyan**
copypasta from https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/hosts.txt

### CODE REVIEW

**Review by pmeenan — APPROVED** [review]
LGTM

**Comment by mjkozicki** [comment]
@pmeenan This is an older PR, is it still valid?

**Comment by pmeenan** [comment]
Yep, looking at the source, that's still the latest update.  Miners abusing the system haven't been a problem recently so it's less urgent, particularly since the login requirements and rate-limiting but it's a good idea to keep ahead of them.

**Comment by stoyan** [comment]
I never merged this because I have not tested it in a real set up. Looks safe but I was extra paranoid.

**Pull request merged**
